# CI Name
name: 'Deployment'

# Only running when
on:
  push:
    branches:
      - master

jobs:
  build:
    # Running on latest version of Ubuntu
    runs-on: ubuntu-latest

    steps:
      # This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Setup Node for Installing Dependencies
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Installing Dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint
  push-hub:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      run: | 
        echo "Login to codelabs.azurecr.io ......"
        echo ${{ secrets.ACR_PASSWORD }} | docker login codelabs.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        echo "Building Image with Tag {{github.sha}}, lastest"
        docker build -t codelabs.azurecr.io/web-codelabs-api:${{ github.sha }} -t codelabs.azurecr.io/web-codelabs-api:lastest .
        echo "Push Image to codelabs.azurecr.io/web-codelabs-api ......."
        docker push codelabs.azurecr.io/web-codelabs-api --all-tags
